spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    schemas:
      - public
      - list
    baseline-on-migrate: true

server:
  port: 8081

logging:
  level:
    sql: info

jwt:
  secret: 17e0710f07f2efc0d0ac915defaebc08a2aea6c1f493622c67d8ce7c42dfb5b1